### ISSUE TITLE
ITK_OVERRIDE Macro in wrong place

### ISSUE THREAD

**Issue by spinicist** [blowekamp/itkOBBLabelMap#1]
Hi,

I am trying out this Module in a project I build with C++11 enabled. I think it picked up a misplaced ITK_OVERRIDE macro - line 116 of itkOrientedBoundingBoxImageLabelMapFilter.h should be:

virtual void VerifyInputInformation() ITK_OVERRIDE {}

instead of

virtual void VerifyInputInformation() {} ITK_OVERRIDE

I think? It compiled fine after I moved the macro.

**Comment by blowekamp** [comment]
You look correct there!

Do you have a pull request with the change?

**Comment by spinicist** [comment]
I just made one. Let me know if it needs changing in some way.

**Comment by blowekamp** [comment]
Fix with pull request.
